apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      myappname: nginxproxyserver
  template:
    metadata:
      labels:
        myappname: nginxproxyserver
    spec:
      containers:
        - name: nginxcontainer
          image: k8s.gcr.io/hpa-example
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
