apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: podhpa
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  targetCPUUtilizationPercentage: 30
